Feature/header
MihailPtash/site pull request #3
Opened 2019-08-23 08:11 UTC by MihailPtash

Начал Работать над Header...

2019-08-26 21:07 UTC, id-spark requested changes
Беда с отступами как в css, так и в html файлах

2019-08-26 21:14 UTC, id-spark requested changes

2019-08-26 21:14 UTC, id-spark commented on css/header.css
> +@import "http://fonts.fontstorage.com/import/nexaslab.css";
Если ты тут импортируешь шрифты с внешнего ресурса, зачем хранишь их локально?

2019-08-26 21:14 UTC, id-spark commented on css/header.css
> +.point1 {
Зачем задублировал стили для каждой точки? Достаточно одного класса point

2019-08-26 21:14 UTC, id-spark commented on css/header.css
> +.menu:hover  ~.point1{
Аналогично, можно обойтись одним блоком

2019-08-26 21:14 UTC, id-spark commented on index.html
> +                     <p class="menu">Blog</p>
Использовать тут <p> неправильно, этот тег предназначен для текстовых блоков - имеются в виду абзацы статей или отдельные куски текстовой информации. Здесь лучше использовать <span> или <div>

2019-08-26 21:14 UTC, id-spark commented on index.html
> +                        <p class="menu1">Fonts</p>
Числовые суффиксы не нужны, у тебя есть набор однотипных элементов, фишка как раз в том, чтобы для всех них использовать один класс и описать таким образом стили сразу для всех элементов с этим классом

2019-08-26 21:14 UTC, id-spark commented on index.html
> +                <ul class="spisok">
Что такое spisok? Нет такого слова в английском языке)

2019-08-26 21:32 UTC, MihailPtash commented on css/header.css
> +@import "http://fonts.fontstorage.com/import/nexaslab.css";
Согласен забыл удалить)

2019-08-27 07:47 UTC, id-spark approved these changes

2019-08-27 07:49 UTC, merged